In [1]:
# Numpy
# Numerical Python
# 고성능 수치 계산을 위한 라이브러리
# 벡터나 행렬 연산에 편리한 기능 제공
# 모든 원소는 같은 자료형만 가능

In [2]:
import numpy as np
a = np.arange( 15 )
print( a )
a = a.reshape( 3, 5, order='F' ) #C행부터 할당 F열부터 할당 
print( a )
print( type ( a ) )
print( a.shape )
print( a.dtype )
print( a.ndim )
print( a.size )

print( dir ( np ) )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
<class 'numpy.ndarray'>
(3, 5)
int32
2
15
['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__',

In [3]:
for i in range( 10 ):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [4]:
print ( a )

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [5]:
b = [-1, 2, 0, 2, 11, -81, 5, 0, -4, 13] #List
print( type ( b ) )
b = np.array( b )
print( type ( b ) )

t = ( 1, 2, 3, 4)  #tuple
print( t )
t = np.array ( t )
print( type ( t ) )

<class 'list'>
<class 'numpy.ndarray'>
(1, 2, 3, 4)
<class 'numpy.ndarray'>


In [6]:
print( b. shape )
print( b. ndim )
print( b. dtype)

# print( help( np.arange ) )

print( np.abs ( b ) ) #절대값 
# print( np.sqrt( b  ) )  제곱근 
print( np.sqrt( np.abs( b ) ) ) #절대값으로 바꾼 자료가 넘어온다 (총 3개 함수)
print ( np.square( b ) ) #제곱하기 
print ( np.isnan( b ) ) #nan이냐 
print ( np. sum ( b ) ) #합계
print ( np. mean ( b ) ) #평균
print ( np. max ( b ) ) #최대값
print ( np. min ( b ) ) #최솟값
print ( np. argmax ( b ) ) #제일 큰 값의 위치값(인덱스)을 알려준다 
print ( np. argmin ( b ) ) #제일 작은 값의 위치값(인덱스)을 알려준다
print ( np. sort ( b ) ) #정렬 오름차순
print ( np. sort ( b ) [::-1] ) #정렬 내림차순 (거꾸로 바꿔주기) [시간:끝:증강값(간격)]
print ( np. median ( b ) ) #중앙값 

(10,)
1
int32
[ 1  2  0  2 11 81  5  0  4 13]
[1.         1.41421356 0.         1.41421356 3.31662479 9.
 2.23606798 0.         2.         3.60555128]
[   1    4    0    4  121 6561   25    0   16  169]
[False False False False False False False False False False]
-53
-5.3
13
-81
9
5
[-81  -4  -1   0   0   2   2   5  11  13]
[ 13  11   5   2   2   0   0  -1  -4 -81]
1.0


---

In [8]:
# 2차원 데이터로 만들기 

In [9]:
c = [ [ 1, 2, 3 ], [4, 5, 6] ]
print ( c )
print ( type ( c ) )
c = np.array( c )
print ( type ( c ) )
print ( c )

print ( np.sum ( c ) )
print ( np.sum ( c, axis=0 ) )
print ( np.sum ( c, axis=1 ) )
print ( np.mean ( c ) )
print ( np.mean ( c, axis=0 ) )
print ( np.mean ( c, axis=1 ) )
print ( np.median ( c ) )
print ( np.median ( c, axis=0 ) )
print ( np.median ( c, axis=1 ) )

print ( np.std ( c ) ) #표준편차
print ( np.var ( c ) ) #분산 

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
[2.5 3.5 4.5]
[2. 5.]
1.707825127659933
2.9166666666666665


In [10]:
# element wise
d = [10, 20, 30, 40, 50]
# print( d + 2 )  error case
d = np.array( d )
print(d + 2)

e = np.array( [ 1, 2, 3, 4, 5] )
print( d + e )
print( d ** e )
print( d * np.sin( d ) )
print( d > 35 )

print( np.add( d, e ) )
print( np.subtract( d, e ) )
print( np.multiply( d, e ) )
print( np.divide( d, e ) )

[12 22 32 42 52]
[11 22 33 44 55]
[       10       400     27000   2560000 312500000]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [11]:
f= np.array( [ 0, 1], [1, 1] )
g = np.array( [ 2, 0], [3, 4] )
print(f*g) #그냥 곱셈 
print(f@g) #행렬곱

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [ ]:
h = np.zeros(10)
print(h)
i = np.zeros( ( 5, 5 ))
print(i)
j = np.ones ( 10 )
print(j)

In [ ]:
k = np.random.random(10)*100
k = [int(i) for i in k]
print( type ( k ) )
print( k )

print(np.random.randint(10, 20))
print(np.random.rand(10))

In [ ]:
# 슬라이싱
m = [i for i in range(10, 20) ]
print( m[0:5])
print( m[0:5:2])
print( m[:])
print( m[:-1])

# ndarray
w = np.arange(10, 20)
print( w[0:5] )
print( w[0:5:2] )

In [ ]:
r = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]
print(r[2][2])
print(r[:][:])
print(r[2][:])
print(r[:2][:1])

# print(r[:, :]) error

s = np.arange(1, 16).reshape(3,5)
print(s)
print(s[2][2])
print(s[:][:])
print(s[:, :])
print(s[:2, :2])
print(s[::-1, ::-1])
print(s[[0,2]])
print(s[:,[1,3,4]]) #행은 다가져오고, 열은 1,3,4열로 가져와
print(s[[0,2],[3,4]]) #0행의 3열, 2행의 4열 데이터 하나를 가져와

In [ ]:
# 전치 행렬
print(s)       #3행 5열
print(s.T)     #5행 3열

In [16]:
# 결합 / 분리
a = [1,2,3]
b = [4,5,6]
for ab in zip(a,b) :
    print(ab)
print(list(zip(a, b)))
print(a+b)
print(a*2)
#print(a+2)  에러

(1, 4)
(2, 5)
(3, 6)
[(1, 4), (2, 5), (3, 6)]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [30]:
e = np.floor(np.random.rand(2, 15) * 100)
print(e)
print(np.hsplit(e, 3))  #3개로 잘라라
for arr in np.hsplit(e,3) :
    print(arr)
for arr in np.hsplit(e, (3,7)):   #[0:3]=0,1,2 인덱스 자르고 [3:7] 3~6까지 자르고 [7:] 7번인덱스부터 마지막까지 
    print(arr)

[[97. 60.  4. 40. 81. 11. 15. 81. 20. 24. 20. 65. 95. 37. 14.]
 [ 3. 61. 49. 65.  0. 10. 58. 90.  8. 95. 39. 87. 81. 30. 96.]]
[array([[97., 60.,  4., 40., 81.],
       [ 3., 61., 49., 65.,  0.]]), array([[11., 15., 81., 20., 24.],
       [10., 58., 90.,  8., 95.]]), array([[20., 65., 95., 37., 14.],
       [39., 87., 81., 30., 96.]])]
[[97. 60.  4. 40. 81.]
 [ 3. 61. 49. 65.  0.]]
[[11. 15. 81. 20. 24.]
 [10. 58. 90.  8. 95.]]
[[20. 65. 95. 37. 14.]
 [39. 87. 81. 30. 96.]]
[[97. 60.  4.]
 [ 3. 61. 49.]]
[[40. 81. 11. 15.]
 [65.  0. 10. 58.]]
[[81. 20. 24. 20. 65. 95. 37. 14.]
 [90.  8. 95. 39. 87. 81. 30. 96.]]


In [48]:
f = np.array([1,2,3,4,5])
g = np.array(['a','b','c','d','e'])
h = np.array([True, True, False, False, True])
# 삼항연산  조건?참:거짓
#          (참일떄실행할 것) IF (조건) else (거짓일때실행할것)

# print([[x,y,z] for x,y,z in zip(f,g,h)])

print([x if z else y for x,y,z in zip(f,g,h)])
print(np.where(h, f, g))
print(np.where(f <3, '작아용', '커용'))
print(np.where(h, '참','거짓'))

[1, 2, 'c', 'd', 5]
['1' '2' 'c' 'd' '5']
['작아용' '작아용' '커용' '커용' '커용']
['참' '참' '거짓' '거짓' '참']


In [68]:
#저장할떄
i = np.arange(10)
np.save('i.npy', i)

#꺼내 쓸 떄
ii = np.load('i.npy')
print(ii)
print(type(ii))

#여러개 파일 넣을 떄
j = np.arang(10)
k = np.arang(20)
np.savez('jk.npz', x=j, y=k)
jk = np.load('jk.npz')
print(type(jk))
print(jk['x'])
print(jk['y'])

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


AttributeError: module 'numpy' has no attribute 'arang'